### ISSUE TITLE
Page cannot open

### ISSUE THREAD

**Issue by vmpowercli** [trackit/trackit#247]
I have installed the trackit on a Centos 7 VM and I can see all docker container are up and running.But whenever i tried to connecto the api page via locahost, it shows page cannot connect  or open

 curl localhost:8580
404 page not found

Can someone please  help me out here 

Thank You

**Comment by hug33k** [comment]
Hi @vmpowercli,

It looks like there is a mistake in our README.md, you should try to use `curl` on `localhost:8080` instead of `localhost:8580`.
I will update the documentation.

Let me know if you are able to make request to the API, so I can close this issue.

Thanks

**Comment by vmpowercli** [comment]
Same issue
 curl localhost:8080
404 page not found

**Comment by vmpowercli** [comment]
Here are the currrent listening ports on the server 
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      10604/docker-proxy-
tcp        0      0 127.0.0.1:6379          0.0.0.0:*               LISTEN      10641/docker-proxy-
tcp        0      0 127.0.0.1:8080          0.0.0.0:*               LISTEN      10867/docker-proxy-
tcp        0      0 127.0.0.1:9200          0.0.0.0:*               LISTEN      10679/docker-proxy-

**Comment by vmpowercli** [comment]
Any help would be appreciated!!

**Comment by cruffinoni** [comment]
> Same issue
> curl localhost:8080
> 404 page not found

You may ping one of the existing route to be sure everything works fine: `curl localhost:8080/docs` 
**EDIT:** Here you will find a list of all the routes handled by the API: https://docs.trackit.io/
